# this is for connecting class from turtlebot_env.py

from turtlebot_env.envs.turtlebot_env_0 import TurtleBotEnv_0
from turtlebot_env.envs.turtlebot_env_fuzzy_1 import TurtleBotEnv_FuzzyReward_1
from turtlebot_env.envs.turtlebot_env_2 import TurtleBotEnv_2
from turtlebot_env.envs.turtlebot_env_fuzzy_3 import TurtleBotEnv_FuzzyReward_3
from turtlebot_env.envs.turtlebot_env_4 import TurtleBotEnv_4
from turtlebot_env.envs.turtlebot_env_5 import TurtleBotEnv_5